from template.bufferpool import *

START_RID = 0
PAGE_SETS = 16
PAGE_SIZE = 4096
RECORDS_PER_PAGE = PAGE_SIZE / 8
BUFFER_POOL_PAGES = 1073741824  # 1GB buffer pool size
META_DATA_PAGES = 3
PAGES_PER_KEY_DIRECTORY_SET = 5
KEY_DIRECTORY_SET_SIZE = PAGES_PER_KEY_DIRECTORY_SET * PAGE_SIZE
MAX_PAGES_IN_BUFFER = BUFFER_POOL_PAGES/PAGE_SIZE
BASE_RID_TYPE = 0
TAIL_RID_TYPE = 1

def init():
    pass
