from template.lockManager import LockManager

DISK_ACCESS = 40
NEW_BASE_RID_INSERT = 41
NEW_TAIL_RID_UPDATE = 42
BUFFER_POOL_MEM_ASSIGN = 44
BASE_LOADED = 45
TAIL_LOADED = 46
AVAILABLE_PAGE_RANGE = 47
NEXT_TAIL_BLOCK_CALC = 48
PAGES_MEM_MAP_BLOCK = 49
PIN_PAGE_SET = 50
UNPIN_PAGE_SET = 51

LOCK_MANAGER = LockManager()


